In [1]:
import numpy as np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Element wise operations

## 1.1 Basic Operations 

In [12]:
a = np.array([1,2,3,4])
a = a + 1
print(a)

[2 3 4 5]


In [13]:
a ** 2

array([ 4,  9, 16, 25])

## All arithmetic opeartors elementwise

In [17]:
a = np.array([1,2,3,4])
b = np.ones(4) + 1
print(a - b)

[-1.  0.  1.  2.]


In [18]:
print(a*b)

[2. 4. 6. 8.]


In [19]:
# matrix multiplication

c = np.diag([1,2,3,4])

print(c*c)
print("****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## comparision operation

In [20]:
a = np.array([1,2,3,4])
b = np.array([5,2,1,4])

a == b

array([False,  True, False,  True])

In [21]:
a > b

array([False, False,  True, False])

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,2,1,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [23]:
np.array_equal(a,c)

True

## logical operatation

In [24]:
a = np.array([1,0,0,1] , dtype = bool)
b = np.array([1,1,0,0] , dtype = bool)

np.logical_or(a,b)

array([ True,  True, False,  True])

In [25]:
np.logical_and(a,b)

array([ True, False, False, False])

## Transcedent operators

In [26]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [27]:
np.log(a)

/var/folders/gy/xjm4pgvj1qv72yxtgzksblzw0000gp/T/ipykernel_73700/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## Shape mismatch

In [30]:
a = np.arange(4)

a + np.array([1,4])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic reduction

In [31]:
x = np.array([1,2,3,4])

np.sum(x)

10

In [33]:
# sum in 2d matrix

x = np.array([[1,2],[2,1]])

x

array([[1, 2],
       [2, 1]])

In [38]:
x.sum(axis = 0)  # column wise sum

array([3, 3])

In [39]:
x.sum(axis = 1)  # row wise sum

array([3, 3])

In [40]:
x = np.array([1,2,3])

x.min()

1

In [41]:
x.max()

3

In [42]:
x.argmin()   # return the index of minimum number

0

In [43]:
x.argmax()   # returns the index of maximum number

2

## Logical operations


In [44]:
np.all([True , False, True])   # all must be true

False

In [46]:
np.any([True , False , True])    # any one must be true

True

In [47]:
a = np.zeros((50,50))

np.any(a!=0)

False

In [48]:
np.all(a == 0)

True

In [51]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a<=b) & (b<=c)).all()

True

# Statistics

In [53]:
x = np.array([1,2,3,4])


np.mean(x)

2.5

In [55]:
np.median(x)

2.5

In [56]:
x.std()

1.118033988749895

## Broadcasting

In [61]:
a = np.tile([1,2,3,4],(3,1))
print(a)

print("************")

a = a.T
print(a)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
************
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [62]:
a = np.tile([1,2,3,4],(3,2))
print(a)

print("************")

a = a.T
print(a)

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]
************
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [64]:
a = np.tile([1,2,3,4],(3,1))
b = np.array([0,1,2,3])

a + b

array([[1, 3, 5, 7],
       [1, 3, 5, 7],
       [1, 3, 5, 7]])

In [66]:
a = np.arange(0 , 40 , 10)
a.shape

(4,)

In [69]:
a = a[:, np.newaxis]   # adds a new axis ( 1D to 2D array )
a.shape

(4, 1, 1, 1)

In [70]:
a

array([[[[ 0]]],


       [[[10]]],


       [[[20]]],


       [[[30]]]])

## Flattening the array

In [71]:
a = np.array([[1,2,3] , [1,2,3]])

In [72]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [75]:
a.ravel()   # flattens 2d array to 1D

array([1, 2, 3, 1, 2, 3])

In [76]:
a.T

array([[1, 1],
       [2, 2],
       [3, 3]])

In [77]:
a.T.ravel()

array([1, 1, 2, 2, 3, 3])

## Reshaping

In [78]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [1 2 3]]


In [80]:
b = a.ravel()
print(b)

[1 2 3 1 2 3]


In [81]:
b = b.reshape(2,3)

In [82]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [83]:
b[0 , 0] = 100
a

array([[100,   2,   3],
       [  1,   2,   3]])

## Resizing

In [84]:
a = np.arange(4)

a.resize((8,))

In [85]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])