# Numpy 
- it provides extension package to python for multi dimentional arrays
- designed for scientific co putation

In [2]:
import numpy as np

a = np.array([0,1,2,3])
print(a)


# array to create within a range

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


why it is useful

In [6]:
# python list

L = range(1000)

%timeit [i**2 for i in L]

76.3 µs ± 4.27 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
a = np.arange(1000)

%timeit a**2

1.01 µs ± 35 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# 1. Creating arrays

# 1.1 Manual construction of array

In [8]:
# 1D array

a = np.array([0,1,2,3])

print(a)

[0 1 2 3]


In [9]:
# to find the dimension of the array

a.ndim

1

In [10]:
# to find the shape

a.shape

(4,)

In [11]:
len(a)

4

In [14]:
# 2D, 3D......

a = np.array([[1,2,3],[4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
a.ndim

2

In [17]:
a.shape

(2, 3)

In [19]:
len(a)  # returns the size of the first array

2

In [21]:
c = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])

print(c)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [22]:
c.ndim

3

In [23]:
c.shape

(2, 2, 3)

# 1.2 Function for creating a list

In [24]:
# using array function

# arange is an array-valued version of the built-in python range function

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(1 , 10 , 2) # (start , stop , step)
b

array([1, 3, 5, 7, 9])

In [27]:
# using linespace

a = np.linspace(0, 1, 6)    # (start , stop, number of points)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [29]:
# common arrays

a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
c = np.eye(3)  #return a 2D array with 1 in diagonal and 0 in the other places

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# create array using diag function

a = np.diag([1,2,3,4])   # constructs a diagonal array

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
np.diag(a)

array([1, 2, 3, 4])

In [38]:
# create array using random

# create a array of the given shape and populate it with random samples

a = np.random.rand(4)
a

array([0.45664474, 0.66867104, 0.89128352, 0.00669026])

In [40]:
# standard normal distribution.  gaussian distribution


a = np.random.randn(3)
a

array([ 0.22825585,  1.53659078, -0.54542958])

# Baic datatypes

In [41]:
a = np.arange(10)

a.dtype

dtype('int64')

In [43]:
a = np.arange(10 , dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
# default data type is float for zeros and ones functions


a =np.zeros((3,3))

print(a)

print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [46]:
# other datatypes

d = np.array([1+2j , 2+4j])

print(d.dtype)

complex128


In [47]:
b = np.array([True , False , False, True , True])

print(b.dtype)

bool


In [48]:
s = np.array(["Ram" , "Cheeka" , "Robert"])

print(s.dtype)

<U6


# 3.Indexing and slicing

In [51]:
a = np.arange(10)

print(a[5])

5


In [52]:
a = np.diag([1,2,3,4])

print(a[2,2])

3


In [53]:
a[2,1] = 5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

# Slicing

In [54]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[1:8:2]

array([1, 3, 5, 7])

In [56]:
a = np.arange(10)
a[5:] = 10

a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [58]:
b = np.arange(5)
a[5:] = b[::-1]

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copying values


In [59]:
a = np.arange(10)

b = a[::2]

b

array([0, 2, 4, 6, 8])

In [60]:
np.shares_memory(a,b)

True

In [61]:
b[0] = 10

b

array([10,  2,  4,  6,  8])

In [62]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [63]:
a = np.arange(10)

c = a[::2].copy()  # force a copy
c

array([0, 2, 4, 6, 8])

In [64]:
np.shares_memory(a,c)

False

In [65]:
c[0] = 10
a
# a value doesnt change

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# another method of creating arrays


In [67]:
a = np.random.randint(0,25,15)
a

array([14,  4,  3,  2, 14,  8,  1,  4, 21, 19, 23, 23,  4, 22,  3])

In [68]:
mask = a%2 == 0


In [71]:
extract_from_a = a[mask]   # it applies mask operation on a
extract_from_a

array([14,  4,  2, 14,  8,  4,  4, 22])

In [72]:
a[mask] = -1
a
# even numbers will be -1 now

array([-1, -1,  3, -1, -1, -1,  1, -1, 21, 19, 23, 23, -1, -1,  3])

In [76]:
# indexing in arrays

a = np.arange(0,100,10)
a



array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [77]:
# accessing values

a[[1,2,3,4]]

array([10, 20, 30, 40])

In [78]:
a[[9,7]] = 100
a

array([  0,  10,  20,  30,  40,  50,  60, 100,  80, 100])